version: '3.8'
services:
  psql:
    container_name: postgresql
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ~/apps/psql:/var/lib/postgresql/data
